### ISSUE TITLE
No scrollbar if the window is too small on the Autobone page

### ISSUE THREAD

**Issue by loucass003** [SlimeVR/SlimeVR-Server#1070]
![image](https://github.com/SlimeVR/SlimeVR-Server/assets/3948904/f3388a77-fd0a-4bf1-8bc3-490353a4f42a)

**Comment by ZycaR** [comment]
Should be fixed in: [GUI - Tracker assignment options](https://github.com/SlimeVR/SlimeVR-Server/pull/1009)
with commit: [Relocate warning message, add scrollbar to layout for overflowing content](https://github.com/SlimeVR/SlimeVR-Server/pull/1009/commits/bbd2afda80c44b78d2026d097a1b9f376618ecea)

![image](https://github.com/SlimeVR/SlimeVR-Server/assets/11602729/89560cc8-2bb9-4714-95d4-153a59689d0d)
