### ISSUE TITLE
add another protocol USB com port 

### ISSUE THREAD

**Issue by Carlos1Eduardo1Colpo** [SlimeVR/SlimeVR-Server#108]
instead of connecting via wi-fi, you can use any Arduino with an IMU

**Comment by ButterscotchVanilla** [comment]
Would this properly support enough trackers?

**Comment by Carlos1Eduardo1Colpo** [comment]
I think so and there are also USB hubs

**Comment by Eirenliel** [comment]
This might be added when USB dongle support is implemented

**Comment by Carlos1Eduardo1Colpo** [comment]
I think the operating system takes care of these things, just select the input with and it should work, it would be like changing ip just select the correct device

**Comment by Eirenliel** [comment]
That's not what I meant. When we implement dongle support we will add serial protocol in firmware and software, so it could be used for this later too.

**Comment by Kamilake** [comment]
Obviously, other users can have a separate USB bridge, such as FT232 .
However, since it cannot be added to the support list forever, I want to have the user manually select the tracker in the following ways.

![image](https://user-images.githubusercontent.com/15166740/154914088-1d3816f3-5432-4cd0-8597-411653a3b4f3.png)

How about this? Is it OK? That only appears when the tracker is not found and usually works the same as before.

**Comment by Eirenliel** [comment]
There will be a serial protocol to distinguish trackers from non-trackers, see #112 so it won't depend on hardware at all

**Comment by unlogisch04** [comment]
We should add a filter for "USB Serial Port (COM[0-9]*)" FT232 chip set shows up as this.

**Comment by ImUrX** [comment]
We implemented USB-HID support now in #913
