### ISSUE TITLE
SlimeVR server cannot find when I turn off and on the IMU device

### ISSUE THREAD

**Issue by ryanmerit** [SlimeVR/SlimeVR-Server#247]
I'm testing the SlimeVR server with several IMU devices, however when I turned off the IMU, and later turn on, the server cannot find the device. Interesting thing is, when I use the command prompt and type "arp -a" for whole devices on the same internet, it doesn't show up the device I turned off.
Is this the problem caused by the firmware, or do I need something else in the configuration?
Please help me to fix this problem

**Comment by unlogisch04** [comment]
I think i don't understand everything here. Can you confirm the sequence:
1. Start SlimeVR Server
2. Power on the Tracker
3. SlimeVR Server sees the Tracker
4. Power off the tracker
5. SlimeVR Server shows the Tracker as disconnected
6. Power on the tracker
7. SlimeVR Server does not show the tracker

I would recommend also to look at the Serial Monitor of this tracker. There you will see, if the Tracker has problems connecting to the Server or the Wifi. (On the Old Gui its the WiFi Window)
To be able to see everything you may have to press the Reset Button on the D1 Mini after you did open the Serial Monitor.

I also can recommend the #technical-support in the discord or the support-forum in there. https://discord.gg/SlimeVR

**Comment by sweetjustin0717** [comment]
Thanks, @unlogisch04 
Please bear with me with my current situation, it's weird for now, but I thought it's important to share my problem with others.
Currently I'm using 6 IMU devices.

1. IMUs are all on, Router is on. I turn on the server and it displays the IMUs are connected. I turn off the IMU, status is disconnected, and then I turn on a few seconds later,  still disconnected.  When I try "arp -a"   , the device I turned off is never shown in the IP address table. Seems like it changed ip address itself or it has been removed  from the router IP table. It's kind of random, but sometimes its IP address changes to 169.254.*.* which only happens when the device cannot find the router. IP router might have a problem

2. So I reset the router, and I wait for few minutes, and try every 6 IMU devices trying to connect, between 1 to 5 times after I try to reconnect, it barely connect to the device.

Seems like the router has a serious problem.

**Comment by unlogisch04** [comment]
I guess this issue is related to [ #203](https://github.com/SlimeVR/SlimeVR-Tracker-ESP/issues/203)

**Comment by ButterscotchV** [comment]
Is this still an issue?

**Comment by ryanmerit** [comment]
Not at all
